skip_terra_cache: False

model:
  model_name: resnet
  arch: resnet50
  dropout: 0
  pretrained: True
  resume_ckpt: False

train:
  seed: 123
  method: "erm" # ["erm", "gazecon"]
  contrastive_weight: 0.5
  gaze_encoder_config:
    num_layers: 2
    hidden_size: 128
    encoder: "transformer"
    nheads: 8
    bidirectional: False
    T: 50
    
  epochs: 50
  batch_size: 32
  lr: 1e-5
  wd: 0
  valid_split: test
  gaze_split: True
  val_check_interval: 8
  loss:
    criterion: "cross_entropy"
    gdro: False
    gdro_config:
      alpha: 0.01
      gamma: 0.1
      min_var_weight: 0
      robust_step_size: 0.01
      use_normalized_loss: False
      btl: False

dataset:
  num_workers: 4
  id_column: "id"
  input_column: "input"
  target_column: "target"
  subgroup_columns: ["chest_tube"]

wandb:
  project: domino
  group: ''
  log_model: False

