# Job to submit a Ray program from a pod outside a running Ray cluster.
apiVersion: batch/v1
kind: Job
metadata:
  name: ray-test-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ray
          image: rayproject/ray:nightly-py38
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "conda activate domino &&
              python job_example.py"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi