model:
  model_name: resnet
  arch: resnet50

train:
  multiclass: False # if true, then uses subgroup columns as multiclass labels
  epochs: 50
  batch_size: 32
  lr: 1e-5
  wd: 0.0
  valid_split: test
  gaze_split: False
  val_check_interval: 5
  loss:
    criterion: "cross_entropy"
    reweight_class_alpha: 10
    reweight_class: False
    robust_sampler: False
    gdro: False
    alpha: 0.01
    gamma: 0.1
    min_var_weight: 0
    robust_step_size: 0.01
    use_normalized_loss: False
    btl: False

dataset:
  num_workers: 4
  id_column: "image_id"
  input_column: "input"
  target_column: "pmx"
  subgroup_columns: []
  datapanel_pth: "/media/4tb_hdd/siim/mimic_dp_08-24-21.dp"

wandb:
  project: domino
  group: ''
  log_model: False

